---
abstract: 'Common libraries for the L<Pinto> suite'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@stratopan.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Module::Build: 0.3601
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300032, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pinto-Common
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Pinto::Common:
    file: lib/Pinto/Common.pm
    version: 0.070
  Pinto::Constants:
    file: lib/Pinto/Constants.pm
    version: 0.070
  Pinto::DistributionSpec:
    file: lib/Pinto/DistributionSpec.pm
    version: 0.070
  Pinto::Exception:
    file: lib/Pinto/Exception.pm
    version: 0.070
  Pinto::Globals:
    file: lib/Pinto/Globals.pm
    version: 0.070
  Pinto::Manual:
    file: lib/Pinto/Manual.pod
    version: 0.070
  Pinto::Manual::Installing:
    file: lib/Pinto/Manual/Installing.pod
    version: 0.070
  Pinto::Manual::Introduction:
    file: lib/Pinto/Manual/Introduction.pod
    version: 0.070
  Pinto::Manual::QuickStart:
    file: lib/Pinto/Manual/QuickStart.pod
    version: 0.070
  Pinto::Manual::Tutorial:
    file: lib/Pinto/Manual/Tutorial.pod
    version: 0.070
  Pinto::PackageSpec:
    file: lib/Pinto/PackageSpec.pm
    version: 0.070
  Pinto::Role::PauseConfig:
    file: lib/Pinto/Role/PauseConfig.pm
    version: 0.070
  Pinto::SpecFactory:
    file: lib/Pinto/SpecFactory.pm
    version: 0.070
  Pinto::Types:
    file: lib/Pinto/Types.pm
    version: 0.070
  Pinto::Util:
    file: lib/Pinto/Util.pm
    version: 0.070
requires:
  Carp: 0
  Class::Load: 0
  DateTime: 0
  Digest::MD5: 0
  Digest::SHA: 0
  English: 0
  Exporter: 0
  File::HomeDir: 0
  IO::File: 0
  IO::Handle: 0
  IO::Interactive: 0
  IO::String: 0
  Module::CoreList: 2.85
  Moose: 0
  Moose::Role: 0
  MooseX::MarkAsMethods: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  Path::Class: 0
  Path::Class::Dir: 0
  Path::Class::File: 0
  Readonly: 0
  Scalar::Util: 0
  Throwable::Error: 0
  URI: 0
  UUID::Tiny: 0
  base: 0
  namespace::autoclean: 0
  overload: 0
  perl: 5.008
  strict: 0
  version: 0
  warnings: 0
resources:
  bugtracker: https://github.com/thaljef/Pinto-Common/issues
  homepage: https://metacpan.org/module/Pinto::Manual
  repository: git://github.com/thaljef/Pinto-Common.git
version: 0.070
