---
abstract: 'Common modules for the pinto-* utilities'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Module::Build: 0.3601
  Moose: 0
  Path::Class: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pinto-Common
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Pinto::Common:
    file: lib/Pinto/Common.pm
    version: 0.019
  Pinto::Constants:
    file: lib/Pinto/Constants.pm
    version: 0.019
  Pinto::Types:
    file: lib/Pinto/Types.pm
    version: 0.019
requires:
  Exporter: 0
  File::HomeDir: 0
  IO::File: 0
  IO::Handle: 0
  IO::String: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  Path::Class::Dir: 0
  Path::Class::File: 0
  Readonly: 0
  URI: 0
  base: 0
  namespace::autoclean: 0
  perl: 5.008
  strict: 0
  version: 0
  warnings: 0
resources:
  bugtracker: https://github.com/thaljef/Pinto-Common/issues
  repository: git://github.com/thaljef/Pinto-Common.git
version: 0.019
