---
abstract: 'Common modules for the pinto-* utilities'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pinto-Common
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Pinto::Common:
    file: lib/Pinto/Common.pm
    version: 0.013
  Pinto::Config:
    file: lib/Pinto/Config.pm
    version: 0.013
  Pinto::Logger:
    file: lib/Pinto/Logger.pm
    version: 0.013
  Pinto::Role::Configurable:
    file: lib/Pinto/Role/Configurable.pm
    version: 0.013
  Pinto::Role::Loggable:
    file: lib/Pinto/Role/Loggable.pm
    version: 0.013
  Pinto::Types:
    file: lib/Pinto/Types.pm
    version: 0.013
requires:
  Carp: 0
  English: 0
  File::HomeDir: 0
  IO::File: 0
  IO::Handle: 0
  IO::String: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Configuration: 0
  MooseX::LazyRequire: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  Path::Class: 0
  Path::Class::Dir: 0
  Path::Class::File: 0
  Readonly: 0
  URI: 0
  namespace::autoclean: 0
  perl: 5.006
resources:
  homepage: https://github.com/thaljef/Pinto-Common
  repository: https://github.com/thaljef/Pinto-Common
version: 0.013
