---
abstract: 'Common modules for the pinto-* utilities'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Module::Build: 0.3601
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pinto-Common
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Pinto::Common:
    file: lib/Pinto/Common.pm
    version: 0.040_001
  Pinto::Constants:
    file: lib/Pinto/Constants.pm
    version: 0.040_001
  Pinto::DistributionSpec:
    file: lib/Pinto/DistributionSpec.pm
    version: 0.040_001
  Pinto::Meta::Attribute::Trait::Postable:
    file: lib/Pinto/Meta/Attribute/Trait/Postable.pm
    version: 0.040_001
  Pinto::PackageSpec:
    file: lib/Pinto/PackageSpec.pm
    version: 0.040_001
  Pinto::Role::Attribute::archives:
    file: lib/Pinto/Role/Attribute/archives.pm
    version: 0.040_001
  Pinto::Role::Attribute::author:
    file: lib/Pinto/Role/Attribute/author.pm
    version: 0.040_001
  Pinto::Role::Attribute::description:
    file: lib/Pinto/Role/Attribute/description.pm
    version: 0.040_001
  Pinto::Role::Attribute::norecurse:
    file: lib/Pinto/Role/Attribute/norecurse.pm
    version: 0.040_001
  Pinto::Role::Attribute::out:
    file: lib/Pinto/Role/Attribute/out.pm
    version: 0.040_001
  Pinto::Role::Attribute::pausecfg:
    file: lib/Pinto/Role/Attribute/pausecfg.pm
    version: 0.040_001
  Pinto::Role::Attribute::pin:
    file: lib/Pinto/Role/Attribute/pin.pm
    version: 0.040_001
  Pinto::Role::Attribute::stack:
    file: lib/Pinto/Role/Attribute/stack.pm
    version: 0.040_001
  Pinto::Role::Attribute::targets:
    file: lib/Pinto/Role/Attribute/targets.pm
    version: 0.040_001
  Pinto::Role::Attribute::username:
    file: lib/Pinto/Role/Attribute/username.pm
    version: 0.040_001
  Pinto::Role::Interface::Action:
    file: lib/Pinto/Role/Interface/Action.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::Add:
    file: lib/Pinto/Role/Interface/Action/Add.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::List:
    file: lib/Pinto/Role/Interface/Action/List.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::Nop:
    file: lib/Pinto/Role/Interface/Action/Nop.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::Pin:
    file: lib/Pinto/Role/Interface/Action/Pin.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::Pull:
    file: lib/Pinto/Role/Interface/Action/Pull.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::Stack::Copy:
    file: lib/Pinto/Role/Interface/Action/Stack/Copy.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::Stack::Create:
    file: lib/Pinto/Role/Interface/Action/Stack/Create.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::Stack::Edit:
    file: lib/Pinto/Role/Interface/Action/Stack/Edit.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::Stack::List:
    file: lib/Pinto/Role/Interface/Action/Stack/List.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::Stack::Log:
    file: lib/Pinto/Role/Interface/Action/Stack/Log.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::Stack::Props:
    file: lib/Pinto/Role/Interface/Action/Stack/Props.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::Stack::Remove:
    file: lib/Pinto/Role/Interface/Action/Stack/Remove.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::Statistics:
    file: lib/Pinto/Role/Interface/Action/Statistics.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::Unpin:
    file: lib/Pinto/Role/Interface/Action/Unpin.pm
    version: 0.040_001
  Pinto::Role::Interface::Action::Verify:
    file: lib/Pinto/Role/Interface/Action/Verify.pm
    version: 0.040_001
  Pinto::Types:
    file: lib/Pinto/Types.pm
    version: 0.040_001
requires:
  Carp: 0
  Class::Load: 0
  Exporter: 0
  File::HomeDir: 0
  IO::File: 0
  IO::Handle: 0
  IO::String: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  Path::Class: 0
  Path::Class::Dir: 0
  Path::Class::File: 0
  Readonly: 0
  URI: 0
  base: 0
  namespace::autoclean: 0
  overload: 0
  perl: 5.008
  strict: 0
  version: 0
  warnings: 0
resources:
  bugtracker: https://github.com/thaljef/Pinto-Common/issues
  repository: git://github.com/thaljef/Pinto-Common.git
version: 0.040_001
